### ISSUE TITLE
IOS issue

### ISSUE THREAD

**Issue by Duovili** [uttesh/ngtimeago#3]
I am using this on a phonegape app but its breaking on IOS do you know what the issue might be,

**Comment by uttesh** [comment]
@Duovili  could you please provide any exception/error your getting, i tried phonegap on android its looks fine.

**Comment by Duovili** [comment]
I already solved it. on an iphone the date formate needs to be 0000/00/00 and in my db its 0000-00-00 different formats for different devices.

**Comment by uttesh** [comment]
@Duovili  nice thanks, so plugin is working fine i can close this issue .

**Comment by Duovili** [comment]
yes thanks

**Comment by uttesh** [comment]
if possible share the snap of the page where plugin used i will put in the plugin web on client list.
