### ISSUE TITLE
Not working in Firefox & Safari using ng-repeat

### ISSUE THREAD

**Issue by xandorxicay** [uttesh/ngtimeago#4]

**Comment by uttesh** [comment]
@xandorxicay is working fine?

**Comment by xandorxicay** [comment]
Yes my bad, It was an error with the format i had firefox did not like it. However,  it be nice to have a function to convert any date to the standard iso_8601 see here for more info http://stackoverflow.com/questions/2573521/how-do-i-output-an-iso-8601-formatted-string-in-javascript

**Comment by uttesh** [comment]
@xandorxicay thanks, i will try to add that function, nice to know about that.
